name: WordPress Plugin Scaffold

on:
  push:
    branches:
      - main

jobs:
  scaffold-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run WP-CLI Scaffold Inside Docker with Increased Memory
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/var/www/html \
            --user $(id -u):$(id -g) \
            wordpress:cli bash -c "
              echo 'memory_limit = 512M' > /usr/local/etc/php/conf.d/memory.ini &&
              wp core download --quiet &&
              wp scaffold plugin my-plugin --plugin_name='My Plugin' --author='Your Name'
            "

      - name: List scaffolded files
        run: ls -R my-plugin
