name: WordPress Plugin Scaffold

on:
  push:
    branches:
      - main

jobs:
  scaffold-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Scaffold Plugin with WP-CLI in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/var/www/html \
            -e PHP_INI_SCAN_DIR=/var/www/html/php-conf:/usr/local/etc/php/conf.d \
            wordpress:cli bash -c "
              mkdir -p /var/www/html/php-conf &&
              echo 'memory_limit = 512M' > /var/www/html/php-conf/memory.ini &&
              wp core download --quiet &&
              wp scaffold plugin my-plugin --plugin_name='My Plugin' --author='Your Name'
            "

      - name: List Scaffolded Files
        run: ls -R my-plugin
